# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create([
  {
    username: 'user001',
    email: 'user001@example.com',
    password: 'Secret1',
    password_confirmation: 'Secret1'
  },
  {
    username: 'user002',
    email: 'user002@example.com',
    password: 'Secret1',
    password_confirmation: 'Secret1'
  },
  {
    username: 'user003',
    email: 'user003@example.com',
    password: 'Secret1',
    password_confirmation: 'Secret1'
  }
])

Post.create([
  
{
    title: 'A few ideas for life that you should know!',
    body: 'Maecenas accumsan justo in lectus mollis aliquam. Pellentesque viverra ornare euismod. Donec massa leo, placerat et posuere eget, venenatis et enim. Etiam congue nisi at velit volutpat sollicitudin. Fusce ut venenatis risus. Ut maximus, arcu eget tempor porta, nisi libero pharetra metus, fermentum imperdiet lorem mauris vitae sapien. Aenean vel diam sit amet tortor vulputate commodo. Maecenas volutpat, urna eget pulvinar tristique, felis sem egestas libero, in egestas nibh neque non nulla.
Ut eget sapien tempor purus facilisis sodales sed et lectus. Nunc pulvinar congue posuere. Morbi vestibulum finibus purus sit amet suscipit. Nunc elit odio, elementum eu imperdiet in, accumsan vel velit. Nulla elit ex, efficitur vel convallis rutrum, egestas a ligula. Nunc sit amet orci dolor. Cras massa sapien, auctor et leo non, scelerisque efficitur augue. Nullam aliquet sem eleifend, laoreet metus ut, feugiat augue. Vestibulum a odio et sapien luctus tempus. Integer in tincidunt risus. Phasellus bibendum, metus nec finibus facilisis, ipsum leo gravida eros, vitae malesuada lorem ante sit amet lectus. Morbi tempor lorem ac ante accumsan, sit amet dignissim leo volutpat. Pellentesque lectus justo, finibus nec arcu a, aliquam faucibus nulla. Nam id metus sed felis cursus rutrum. Aenean vel imperdiet erat. Ut sem felis, suscipit vel justo et, commodo feugiat nisl.',
    user_id: User.first.id
  },
{
    title: 'How to drive carefully',
    body: 'Maecenas accumsan justo in lectus mollis aliquam. Pellentesque viverra ornare euismod. Donec massa leo, placerat et posuere eget, venenatis et enim. Etiam congue nisi at velit volutpat sollicitudin. Fusce ut venenatis risus. Ut maximus, arcu eget tempor porta, nisi libero pharetra metus, fermentum imperdiet lorem mauris vitae sapien. Aenean vel diam sit amet tortor vulputate commodo. Maecenas volutpat, urna eget pulvinar tristique, felis sem egestas libero, in egestas nibh neque non nulla.
Ut eget sapien tempor purus facilisis sodales sed et lectus. Nunc pulvinar congue posuere. Morbi vestibulum finibus purus sit amet suscipit. Nunc elit odio, elementum eu imperdiet in, accumsan vel velit. Nulla elit ex, efficitur vel convallis rutrum, egestas a ligula. Nunc sit amet orci dolor. Cras massa sapien, auctor et leo non, scelerisque efficitur augue. Nullam aliquet sem eleifend, laoreet metus ut, feugiat augue. Vestibulum a odio et sapien luctus tempus. Integer in tincidunt risus. Phasellus bibendum, metus nec finibus facilisis, ipsum leo gravida eros, vitae malesuada lorem ante sit amet lectus. Morbi tempor lorem ac ante accumsan, sit amet dignissim leo volutpat. Pellentesque lectus justo, finibus nec arcu a, aliquam faucibus nulla. Nam id metus sed felis cursus rutrum. Aenean vel imperdiet erat. Ut sem felis, suscipit vel justo et, commodo feugiat nisl.',
    user_id: User.second.id
  },
{
    title: 'How to play golf',
    body: 'Ut eget sapien tempor purus facilisis sodales sed et lectus. Nunc pulvinar congue posuere. Morbi vestibulum finibus purus sit amet suscipit. Nunc elit odio, elementum eu imperdiet in, accumsan vel velit. Nulla elit ex, efficitur vel convallis rutrum, egestas a ligula. Nunc sit amet orci dolor. Cras massa sapien, auctor et leo non, scelerisque efficitur augue. Nullam aliquet sem eleifend, laoreet metus ut, feugiat augue. Vestibulum a odio et sapien luctus tempus. Integer in tincidunt risus. Phasellus bibendum, metus nec finibus facilisis, ipsum leo gravida eros, vitae malesuada lorem ante sit amet lectus. Morbi tempor lorem ac ante accumsan, sit amet dignissim leo volutpat. Pellentesque lectus justo, finibus nec arcu a, aliquam faucibus nulla. Nam id metus sed felis cursus rutrum. Aenean vel imperdiet erat. Ut sem felis, suscipit vel justo et, commodo feugiat nisl.',
    user_id: User.third.id
  },
  {
    title: 'Another clever post!',
    body: 'Maecenas accumsan justo in lectus mollis aliquam. Pellentesque viverra ornare euismod. Donec massa leo, placerat et posuere eget, venenatis et enim. Etiam congue nisi at velit volutpat sollicitudin. Fusce ut venenatis risus. Ut maximus, arcu eget tempor porta, nisi libero pharetra metus, fermentum imperdiet lorem mauris vitae sapien. Aenean vel diam sit amet tortor vulputate commodo. Maecenas volutpat, urna eget pulvinar tristique, felis sem egestas libero, in egestas nibh neque non nulla.
Ut eget sapien tempor purus facilisis sodales sed et lectus. Nunc pulvinar congue posuere. Morbi vestibulum finibus purus sit amet suscipit. Nunc elit odio, elementum eu imperdiet in, accumsan vel velit. Nulla elit ex, efficitur vel convallis rutrum, egestas a ligula. Nunc sit amet orci dolor. Cras massa sapien, auctor et leo non, scelerisque efficitur augue. Nullam aliquet sem eleifend, laoreet metus ut, feugiat augue. Vestibulum a odio et sapien luctus tempus. Integer in tincidunt risus. Phasellus bibendum, metus nec finibus facilisis, ipsum leo gravida eros, vitae malesuada lorem ante sit amet lectus. Morbi tempor lorem ac ante accumsan, sit amet dignissim leo volutpat. Pellentesque lectus justo, finibus nec arcu a, aliquam faucibus nulla. Nam id metus sed felis cursus rutrum. Aenean vel imperdiet erat. Ut sem felis, suscipit vel justo et, commodo feugiat nisl.',
    user_id: User.first.id
  },
  {
    title: 'Interesting ideas about programming',
    body: 'Maecenas accumsan justo in lectus mollis aliquam. Pellentesque viverra ornare euismod. Donec massa leo, placerat et posuere eget, venenatis et enim. Etiam congue nisi at velit volutpat sollicitudin. Fusce ut venenatis risus. Ut maximus, arcu eget tempor porta, nisi libero pharetra metus, fermentum imperdiet lorem mauris vitae sapien. Aenean vel diam sit amet tortor vulputate commodo. Maecenas volutpat, urna eget pulvinar tristique, felis sem egestas libero, in egestas nibh neque non nulla.
Ut eget sapien tempor purus facilisis sodales sed et lectus. Nunc pulvinar congue posuere. Morbi vestibulum finibus purus sit amet suscipit. Nunc elit odio, elementum eu imperdiet in, accumsan vel velit. Nulla elit ex, efficitur vel convallis rutrum, egestas a ligula. Nunc sit amet orci dolor. Cras massa sapien, auctor et leo non, scelerisque efficitur augue. Nullam aliquet sem eleifend, laoreet metus ut, feugiat augue. Vestibulum a odio et sapien luctus tempus. Integer in tincidunt risus. Phasellus bibendum, metus nec finibus facilisis, ipsum leo gravida eros, vitae malesuada lorem ante sit amet lectus. Morbi tempor lorem ac ante accumsan, sit amet dignissim leo volutpat. Pellentesque lectus justo, finibus nec arcu a, aliquam faucibus nulla. Nam id metus sed felis cursus rutrum. Aenean vel imperdiet erat. Ut sem felis, suscipit vel justo et, commodo feugiat nisl.',
    user_id: User.second.id
  },
  {
    title: 'Another post on the wall',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tincidunt convallis ipsum at varius. In urna nisl, pretium a felis eget, tempus lobortis mi. Maecenas a gravida ex. Fusce cursus dignissim neque, ac porttitor dolor semper a. Integer aliquam massa venenatis, pellentesque massa eu, tristique lacus. Etiam quis dictum diam. Cras tempor ac ex eget congue. Cras ex magna, feugiat in scelerisque in, consequat at nisi. Ut enim sem, pharetra a pharetra quis, ullamcorper et elit.
Nulla cursus elementum eros eget scelerisque. Quisque eu lacinia ante. In hac habitasse platea dictumst. Phasellus sodales commodo odio, in viverra dolor scelerisque ac. Phasellus consequat risus ut justo tincidunt rhoncus. Curabitur nec urna at dolor vestibulum scelerisque. Praesent molestie, nisi ac auctor aliquam, mauris eros maximus risus, id porta ex enim in lorem. Ut sed magna dictum, iaculis mauris nec, auctor ligula. Donec vulputate et augue ac blandit. Vestibulum egestas quam sed nulla gravida varius. Sed vulputate semper commodo. Donec vitae purus non tellus aliquam euismod eget at felis.
Cras volutpat tellus id quam aliquam pulvinar. In vel viverra orci. Nam sed iaculis lorem, consectetur porttitor lectus. Nam efficitur quam ut sem efficitur porttitor. Sed sed arcu nisi. Vestibulum mi odio, lacinia non felis in, suscipit faucibus augue. Proin eget orci nibh. Praesent viverra placerat nulla suscipit porta. Praesent mattis purus a lorem tempor, eu dignissim augue commodo. Mauris eleifend, ligula a molestie feugiat, erat mi ultricies odio, ut venenatis est risus a ipsum. Donec ut leo nibh. Fusce molestie sit amet magna quis tincidunt. Curabitur leo nibh, feugiat nec cursus sit amet, hendrerit in enim. In vitae tempus arcu, quis accumsan nisi.
Maecenas accumsan justo in lectus mollis aliquam. Pellentesque viverra ornare euismod. Donec massa leo, placerat et posuere eget, venenatis et enim. Etiam congue nisi at velit volutpat sollicitudin. Fusce ut venenatis risus. Ut maximus, arcu eget tempor porta, nisi libero pharetra metus, fermentum imperdiet lorem mauris vitae sapien. Aenean vel diam sit amet tortor vulputate commodo. Maecenas volutpat, urna eget pulvinar tristique, felis sem egestas libero, in egestas nibh neque non nulla.
Ut eget sapien tempor purus facilisis sodales sed et lectus. Nunc pulvinar congue posuere. Morbi vestibulum finibus purus sit amet suscipit. Nunc elit odio, elementum eu imperdiet in, accumsan vel velit. Nulla elit ex, efficitur vel convallis rutrum, egestas a ligula. Nunc sit amet orci dolor. Cras massa sapien, auctor et leo non, scelerisque efficitur augue. Nullam aliquet sem eleifend, laoreet metus ut, feugiat augue. Vestibulum a odio et sapien luctus tempus. Integer in tincidunt risus. Phasellus bibendum, metus nec finibus facilisis, ipsum leo gravida eros, vitae malesuada lorem ante sit amet lectus. Morbi tempor lorem ac ante accumsan, sit amet dignissim leo volutpat. Pellentesque lectus justo, finibus nec arcu a, aliquam faucibus nulla. Nam id metus sed felis cursus rutrum. Aenean vel imperdiet erat. Ut sem felis, suscipit vel justo et, commodo feugiat nisl.',
    user_id: User.third.id
  },
  {
    title: 'The best ideas for your job searching',
    body: 'Nulla imperdiet turpis at dolor pharetra elementum eu vel ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut egestas felis tellus. Integer quis molestie purus, eget dictum neque. Morbi sit amet volutpat nisi, ut vestibulum enim. In tristique ornare magna, laoreet ullamcorper dui tincidunt sit amet. Sed id quam nec erat auctor malesuada a eu odio. Etiam hendrerit sed magna non maximus. Suspendisse hendrerit orci lectus, a euismod erat mattis in. Sed placerat massa sit amet eros laoreet, eu semper sem pulvinar. Pellentesque elementum imperdiet magna at luctus. Suspendisse ultrices, nulla vehicula luctus imperdiet, purus ante tincidunt neque, non tincidunt nunc turpis hendrerit tortor. Morbi elit velit, sodales mollis lorem in, laoreet porttitor metus.
Integer aliquet ligula lacus, volutpat hendrerit justo ultricies blandit. Aenean lobortis a massa vitae congue. Phasellus non magna consequat, consequat odio vel, placerat tortor. Suspendisse arcu mi, vulputate quis dolor ac, fermentum tempor elit. Pellentesque consectetur, erat ut interdum fringilla, enim nisl aliquam ante, sit amet cursus metus purus id tellus. Nullam at leo ut dui efficitur ultricies eget ac lectus. Vivamus lorem lorem, tempor a quam at, mollis fringilla ante. Sed quis orci sit amet ex pulvinar accumsan.
Nullam ut nisi a nisi rhoncus volutpat sit amet quis elit. Quisque eu elementum sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi blandit, urna et mattis molestie, quam tortor fermentum metus, et efficitur sem diam sed ex. Duis mollis porttitor venenatis. Aenean laoreet tellus eu blandit finibus. Donec dolor libero, lacinia at finibus ac, accumsan ut velit. Vestibulum suscipit lacus sit amet leo luctus luctus. Proin sit amet lectus nec purus fermentum consequat a viverra est. Curabitur vitae metus dolor. Vivamus facilisis vel sem ac rutrum. ',
    user_id: User.first.id
  },
  {
    title: 'How to keep your garden neat and beautiful',
    body: 'Donec placerat ex eros, in tempor lorem malesuada a. Quisque mattis dictum condimentum. Donec mauris nunc, mollis quis nisi imperdiet, vulputate hendrerit magna. Nam urna nulla, accumsan eu urna quis, suscipit laoreet lacus. Vestibulum efficitur tellus finibus augue pulvinar, eu porttitor arcu tempor. Integer elementum, neque non porta efficitur, mauris nibh luctus dui, non ullamcorper felis massa ut felis. Duis finibus ipsum ut lectus maximus pretium. In blandit neque eu convallis pharetra.
Donec a aliquam felis. Quisque magna nisl, tempus ac ante ullamcorper, sollicitudin dictum urna. Quisque et lacus velit. Donec consequat sollicitudin ligula, vitae rutrum lectus tincidunt euismod. Morbi blandit, nisi quis congue molestie, augue purus interdum lacus, eu fermentum nulla eros eu enim. Vestibulum ante est, condimentum quis velit a, maximus sodales mauris. Mauris convallis nec dui consequat lacinia. Curabitur gravida vestibulum justo nec accumsan. Aliquam dictum et leo id gravida. Integer ac pulvinar quam. Praesent rhoncus, nibh eu scelerisque porttitor, felis nulla scelerisque odio, non lobortis nisl augue eu augue. Nunc ultrices mauris felis, nec finibus erat egestas in. Fusce accumsan ullamcorper magna et accumsan. Proin est lorem, consequat vel nulla non, porttitor vulputate est. Pellentesque eu lacinia eros.
In dignissim mi quis ipsum sollicitudin, at suscipit mauris laoreet. Proin enim tortor, rhoncus vel justo sed, iaculis pellentesque tortor. Etiam condimentum suscipit dignissim. Morbi dignissim tincidunt vehicula. Nullam commodo accumsan velit, a iaculis ante vestibulum at. Suspendisse cursus consequat libero a tristique. Donec vel eros et felis faucibus blandit. Donec vitae risus quis elit tristique posuere et quis purus. Pellentesque ultricies tellus turpis, sed hendrerit mauris scelerisque viverra. Quisque ullamcorper quis neque at pharetra. Aliquam tempus placerat justo eget interdum. Suspendisse lobortis scelerisque ex, et vehicula augue suscipit ut. Sed ut tortor vitae ipsum ultrices suscipit ac accumsan diam. Etiam sollicitudin eu nibh quis vehicula. Sed a pulvinar eros.
Praesent nec nisl sem. Cras tempus, augue at placerat scelerisque, eros turpis lacinia augue, id hendrerit purus est et neque. In pulvinar tincidunt enim eu pulvinar. Proin eget tempus metus. Curabitur venenatis dapibus diam, quis pellentesque est semper in. Ut ut turpis egestas, sollicitudin nisl eget, congue ex. Nunc lacus ex, ullamcorper vel aliquam et, imperdiet sed mi. Integer sollicitudin nibh id elit bibendum tincidunt. Quisque malesuada arcu in purus ultricies elementum. Proin nisl lorem, dignissim et est id, sagittis vulputate felis. Vivamus egestas est at ultrices interdum. Pellentesque odio ante, blandit sed aliquam a, accumsan blandit urna. Ut at tempor est, venenatis sollicitudin leo. Morbi tincidunt nisl orci, ac mollis leo sodales sit amet. Pellentesque arcu nulla, imperdiet vitae magna sit amet, blandit consequat libero. Maecenas iaculis ullamcorper maximus.
Duis gravida est a dapibus hendrerit. Cras laoreet lobortis eros in condimentum. Phasellus in mattis sem. Mauris quam est, vehicula sit amet vestibulum id, faucibus in est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin imperdiet posuere enim, vel ultricies erat congue ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus vel diam libero. Vestibulum egestas justo eu massa tempus mattis.
Sed dictum, dolor et elementum tristique, urna sem suscipit lectus, quis pharetra orci leo sit amet turpis. Vivamus sollicitudin bibendum vestibulum. Maecenas tristique, augue eu mattis tempus, diam lacus bibendum lorem, sed ornare odio nibh sed neque. Morbi blandit porttitor felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas non orci sed est finibus blandit id quis quam. Nam a nibh sem. Praesent finibus sodales mauris, sit amet interdum orci dapibus eu. Praesent ultricies, massa vitae maximus ultricies, purus erat tempor ex, et porta tortor metus vel odio. Integer eget eros leo. Nulla in orci ut enim venenatis dapibus. Mauris in dui turpis. Curabitur mollis volutpat erat facilisis aliquet.
Nullam quis purus vitae mi laoreet consequat. Ut at ligula mi. Integer ultrices sit amet erat vitae fringilla. Nulla eleifend tincidunt dui vitae mollis. Maecenas quis lacus et purus sagittis fringilla vitae sit amet leo. Pellentesque ac accumsan neque, congue tincidunt sem. Morbi justo ex, pulvinar vel accumsan sit amet, porttitor sit amet mi. Nullam suscipit id massa eget suscipit. Nulla facilisi. Suspendisse eget velit scelerisque, bibendum diam at, luctus nulla. Duis convallis purus felis, vitae aliquam orci sollicitudin ut. Suspendisse malesuada arcu vitae consectetur commodo. Sed semper lectus non massa porttitor efficitur. Quisque iaculis eu mi sed fringilla. Integer volutpat turpis ut leo sodales, in sagittis ante porta. Nunc vitae molestie tellus, eget venenatis tortor.
Donec non velit quis odio eleifend porttitor non eu ex. Nunc sed libero nec sapien aliquet consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec risus lacus, consequat id purus imperdiet, fringilla dignissim ipsum. Ut neque tellus, finibus ac sodales sit amet, dapibus eu elit. Aliquam at metus quis nulla bibendum egestas. Nunc sit amet elit condimentum, ornare felis non, ullamcorper nisi. Curabitur quis ante tincidunt, efficitur est eu, auctor sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus euismod rhoncus tortor, eget varius metus aliquet ac. Fusce magna ante, tristique iaculis ante eu, convallis vehicula ex. Curabitur egestas tincidunt iaculis. Nunc ac magna auctor quam condimentum malesuada.
Curabitur lobortis, orci at bibendum congue, nisl felis suscipit ligula, quis rutrum orci turpis quis erat. Donec bibendum lectus nec convallis vulputate. In mattis tortor neque, id ullamcorper dolor malesuada et. Morbi dolor lorem, lobortis quis pellentesque ac, condimentum iaculis libero. Fusce neque dui, fringilla quis consequat eu, luctus at diam. Donec orci enim, rhoncus sit amet sem nec, pharetra congue ex. Nunc dolor diam, congue eget sollicitudin quis, condimentum in quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin interdum libero ultricies vestibulum pulvinar. Praesent dapibus tristique nunc vitae posuere.
Donec placerat augue mi, a dictum nibh eleifend id. Mauris eu metus interdum, vestibulum ipsum eu, dignissim felis. Phasellus commodo elementum rutrum. Sed at est fermentum, luctus nulla venenatis, ultricies tortor. Nulla quis purus aliquet, pellentesque orci vitae, dictum lorem. Pellentesque dictum orci nec ipsum finibus laoreet. Curabitur facilisis nibh eget orci laoreet, in convallis turpis aliquet. Aenean aliquam dictum tincidunt.',
    user_id: User.second.id
  },
  {
    title: 'Best practices for life',
    body: 'Donec placerat ex eros, in tempor lorem malesuada a. Quisque mattis dictum condimentum. Donec mauris nunc, mollis quis nisi imperdiet, vulputate hendrerit magna. Nam urna nulla, accumsan eu urna quis, suscipit laoreet lacus. Vestibulum efficitur tellus finibus augue pulvinar, eu porttitor arcu tempor. Integer elementum, neque non porta efficitur, mauris nibh luctus dui, non ullamcorper felis massa ut felis. Duis finibus ipsum ut lectus maximus pretium. In blandit neque eu convallis pharetra.
Donec a aliquam felis. Quisque magna nisl, tempus ac ante ullamcorper, sollicitudin dictum urna. Quisque et lacus velit. Donec consequat sollicitudin ligula, vitae rutrum lectus tincidunt euismod. Morbi blandit, nisi quis congue molestie, augue purus interdum lacus, eu fermentum nulla eros eu enim. Vestibulum ante est, condimentum quis velit a, maximus sodales mauris. Mauris convallis nec dui consequat lacinia. Curabitur gravida vestibulum justo nec accumsan. Aliquam dictum et leo id gravida. Integer ac pulvinar quam. Praesent rhoncus, nibh eu scelerisque porttitor, felis nulla scelerisque odio, non lobortis nisl augue eu augue. Nunc ultrices mauris felis, nec finibus erat egestas in. Fusce accumsan ullamcorper magna et accumsan. Proin est lorem, consequat vel nulla non, porttitor vulputate est. Pellentesque eu lacinia eros.
In dignissim mi quis ipsum sollicitudin, at suscipit mauris laoreet. Proin enim tortor, rhoncus vel justo sed, iaculis pellentesque tortor. Etiam condimentum suscipit dignissim. Morbi dignissim tincidunt vehicula. Nullam commodo accumsan velit, a iaculis ante vestibulum at. Suspendisse cursus consequat libero a tristique. Donec vel eros et felis faucibus blandit. Donec vitae risus quis elit tristique posuere et quis purus. Pellentesque ultricies tellus turpis, sed hendrerit mauris scelerisque viverra. Quisque ullamcorper quis neque at pharetra. Aliquam tempus placerat justo eget interdum. Suspendisse lobortis scelerisque ex, et vehicula augue suscipit ut. Sed ut tortor vitae ipsum ultrices suscipit ac accumsan diam. Etiam sollicitudin eu nibh quis vehicula. Sed a pulvinar eros.
Praesent nec nisl sem. Cras tempus, augue at placerat scelerisque, eros turpis lacinia augue, id hendrerit purus est et neque. In pulvinar tincidunt enim eu pulvinar. Proin eget tempus metus. Curabitur venenatis dapibus diam, quis pellentesque est semper in. Ut ut turpis egestas, sollicitudin nisl eget, congue ex. Nunc lacus ex, ullamcorper vel aliquam et, imperdiet sed mi. Integer sollicitudin nibh id elit bibendum tincidunt. Quisque malesuada arcu in purus ultricies elementum. Proin nisl lorem, dignissim et est id, sagittis vulputate felis. Vivamus egestas est at ultrices interdum. Pellentesque odio ante, blandit sed aliquam a, accumsan blandit urna. Ut at tempor est, venenatis sollicitudin leo. Morbi tincidunt nisl orci, ac mollis leo sodales sit amet. Pellentesque arcu nulla, imperdiet vitae magna sit amet, blandit consequat libero. Maecenas iaculis ullamcorper maximus.
Duis gravida est a dapibus hendrerit. Cras laoreet lobortis eros in condimentum. Phasellus in mattis sem. Mauris quam est, vehicula sit amet vestibulum id, faucibus in est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin imperdiet posuere enim, vel ultricies erat congue ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus vel diam libero. Vestibulum egestas justo eu massa tempus mattis.
Sed dictum, dolor et elementum tristique, urna sem suscipit lectus, quis pharetra orci leo sit amet turpis. Vivamus sollicitudin bibendum vestibulum. Maecenas tristique, augue eu mattis tempus, diam lacus bibendum lorem, sed ornare odio nibh sed neque. Morbi blandit porttitor felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas non orci sed est finibus blandit id quis quam. Nam a nibh sem. Praesent finibus sodales mauris, sit amet interdum orci dapibus eu. Praesent ultricies, massa vitae maximus ultricies, purus erat tempor ex, et porta tortor metus vel odio. Integer eget eros leo. Nulla in orci ut enim venenatis dapibus. Mauris in dui turpis. Curabitur mollis volutpat erat facilisis aliquet.
Nullam quis purus vitae mi laoreet consequat. Ut at ligula mi. Integer ultrices sit amet erat vitae fringilla. Nulla eleifend tincidunt dui vitae mollis. Maecenas quis lacus et purus sagittis fringilla vitae sit amet leo. Pellentesque ac accumsan neque, congue tincidunt sem. Morbi justo ex, pulvinar vel accumsan sit amet, porttitor sit amet mi. Nullam suscipit id massa eget suscipit. Nulla facilisi. Suspendisse eget velit scelerisque, bibendum diam at, luctus nulla. Duis convallis purus felis, vitae aliquam orci sollicitudin ut. Suspendisse malesuada arcu vitae consectetur commodo. Sed semper lectus non massa porttitor efficitur. Quisque iaculis eu mi sed fringilla. Integer volutpat turpis ut leo sodales, in sagittis ante porta. Nunc vitae molestie tellus, eget venenatis tortor.
Donec non velit quis odio eleifend porttitor non eu ex. Nunc sed libero nec sapien aliquet consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec risus lacus, consequat id purus imperdiet, fringilla dignissim ipsum. Ut neque tellus, finibus ac sodales sit amet, dapibus eu elit. Aliquam at metus quis nulla bibendum egestas. Nunc sit amet elit condimentum, ornare felis non, ullamcorper nisi. Curabitur quis ante tincidunt, efficitur est eu, auctor sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus euismod rhoncus tortor, eget varius metus aliquet ac. Fusce magna ante, tristique iaculis ante eu, convallis vehicula ex. Curabitur egestas tincidunt iaculis. Nunc ac magna auctor quam condimentum malesuada.
Curabitur lobortis, orci at bibendum congue, nisl felis suscipit ligula, quis rutrum orci turpis quis erat. Donec bibendum lectus nec convallis vulputate. In mattis tortor neque, id ullamcorper dolor malesuada et. Morbi dolor lorem, lobortis quis pellentesque ac, condimentum iaculis libero. Fusce neque dui, fringilla quis consequat eu, luctus at diam. Donec orci enim, rhoncus sit amet sem nec, pharetra congue ex. Nunc dolor diam, congue eget sollicitudin quis, condimentum in quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin interdum libero ultricies vestibulum pulvinar. Praesent dapibus tristique nunc vitae posuere.
Donec placerat augue mi, a dictum nibh eleifend id. Mauris eu metus interdum, vestibulum ipsum eu, dignissim felis. Phasellus commodo elementum rutrum. Sed at est fermentum, luctus nulla venenatis, ultricies tortor. Nulla quis purus aliquet, pellentesque orci vitae, dictum lorem. Pellentesque dictum orci nec ipsum finibus laoreet. Curabitur facilisis nibh eget orci laoreet, in convallis turpis aliquet. Aenean aliquam dictum tincidunt.',
    user_id: User.third.id
  },
  {
    title: 'How to pick the best color theme for your website',
    body: 'Donec placerat ex eros, in tempor lorem malesuada a. Quisque mattis dictum condimentum. Donec mauris nunc, mollis quis nisi imperdiet, vulputate hendrerit magna. Nam urna nulla, accumsan eu urna quis, suscipit laoreet lacus. Vestibulum efficitur tellus finibus augue pulvinar, eu porttitor arcu tempor. Integer elementum, neque non porta efficitur, mauris nibh luctus dui, non ullamcorper felis massa ut felis. Duis finibus ipsum ut lectus maximus pretium. In blandit neque eu convallis pharetra.
Donec a aliquam felis. Quisque magna nisl, tempus ac ante ullamcorper, sollicitudin dictum urna. Quisque et lacus velit. Donec consequat sollicitudin ligula, vitae rutrum lectus tincidunt euismod. Morbi blandit, nisi quis congue molestie, augue purus interdum lacus, eu fermentum nulla eros eu enim. Vestibulum ante est, condimentum quis velit a, maximus sodales mauris. Mauris convallis nec dui consequat lacinia. Curabitur gravida vestibulum justo nec accumsan. Aliquam dictum et leo id gravida. Integer ac pulvinar quam. Praesent rhoncus, nibh eu scelerisque porttitor, felis nulla scelerisque odio, non lobortis nisl augue eu augue. Nunc ultrices mauris felis, nec finibus erat egestas in. Fusce accumsan ullamcorper magna et accumsan. Proin est lorem, consequat vel nulla non, porttitor vulputate est. Pellentesque eu lacinia eros.
In dignissim mi quis ipsum sollicitudin, at suscipit mauris laoreet. Proin enim tortor, rhoncus vel justo sed, iaculis pellentesque tortor. Etiam condimentum suscipit dignissim. Morbi dignissim tincidunt vehicula. Nullam commodo accumsan velit, a iaculis ante vestibulum at. Suspendisse cursus consequat libero a tristique. Donec vel eros et felis faucibus blandit. Donec vitae risus quis elit tristique posuere et quis purus. Pellentesque ultricies tellus turpis, sed hendrerit mauris scelerisque viverra. Quisque ullamcorper quis neque at pharetra. Aliquam tempus placerat justo eget interdum. Suspendisse lobortis scelerisque ex, et vehicula augue suscipit ut. Sed ut tortor vitae ipsum ultrices suscipit ac accumsan diam. Etiam sollicitudin eu nibh quis vehicula. Sed a pulvinar eros.
Donec non velit quis odio eleifend porttitor non eu ex. Nunc sed libero nec sapien aliquet consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec risus lacus, consequat id purus imperdiet, fringilla dignissim ipsum. Ut neque tellus, finibus ac sodales sit amet, dapibus eu elit. Aliquam at metus quis nulla bibendum egestas. Nunc sit amet elit condimentum, ornare felis non, ullamcorper nisi. Curabitur quis ante tincidunt, efficitur est eu, auctor sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus euismod rhoncus tortor, eget varius metus aliquet ac. Fusce magna ante, tristique iaculis ante eu, convallis vehicula ex. Curabitur egestas tincidunt iaculis. Nunc ac magna auctor quam condimentum malesuada.
Curabitur lobortis, orci at bibendum congue, nisl felis suscipit ligula, quis rutrum orci turpis quis erat. Donec bibendum lectus nec convallis vulputate. In mattis tortor neque, id ullamcorper dolor malesuada et. Morbi dolor lorem, lobortis quis pellentesque ac, condimentum iaculis libero. Fusce neque dui, fringilla quis consequat eu, luctus at diam. Donec orci enim, rhoncus sit amet sem nec, pharetra congue ex. Nunc dolor diam, congue eget sollicitudin quis, condimentum in quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin interdum libero ultricies vestibulum pulvinar. Praesent dapibus tristique nunc vitae posuere.
Donec placerat augue mi, a dictum nibh eleifend id. Mauris eu metus interdum, vestibulum ipsum eu, dignissim felis. Phasellus commodo elementum rutrum. Sed at est fermentum, luctus nulla venenatis, ultricies tortor. Nulla quis purus aliquet, pellentesque orci vitae, dictum lorem. Pellentesque dictum orci nec ipsum finibus laoreet. Curabitur facilisis nibh eget orci laoreet, in convallis turpis aliquet. Aenean aliquam dictum tincidunt.',
    user_id: User.first.id
  }
])